# File: .github/workflows/build.yml

name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Configure
        run: cmake .

      - name: Build
        run: make
