# File: .github/workflows/yara.yml

name: YARA Validation

on:
  push:
  pull_request:

jobs:
  yara-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install YARA
        run: |
          sudo apt-get update
          sudo apt-get install -y yara

      - name: Validate YARA rules
        run: |
          find malware-analysis/yara -name "*.yar" -exec yara {} /bin/ls \;
